import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/shared/header/Navbar";

export const metadata: Metadata = {
  title: "Portfolio of Abdul Kader",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={``}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
